---
- name: Include distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_system }}.yml'
    - 'default.yml'

- name: Create repository
  ansible.builtin.include_tasks: Repository.yml

- name: Add package
  ansible.builtin.include_tasks: Package.yml

- name: Add scan
  ansible.builtin.include_tasks: Scan.yml
