---
- name: Include distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_system }}.yml'
    - 'default.yml'

- name: create repository
  include_tasks: repository.yml

- name: add package
  include_tasks: package.yml

- name: add scan
  include_tasks: scan.yml
