---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    molecule_repo_file: "cisofy-lynis"
    molecule_repo_name: "lynis"
    molecule_repo_package: "lynis"

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: "APT | Test if repository exists"
      ansible.builtin.lineinfile:
        name: '/etc/apt/sources.list.d/{{ molecule_repo_file }}.list'
        line: "# lynis community repository"
        state: present
      check_mode: true
      register: molecule_repository
      failed_when: (molecule_repository is changed) or (molecule_repository is failed)
      when:
        - ansible_os_family == "Debian"

    - name: "YUM | Test if repository exists"
      ansible.builtin.lineinfile:
        name: "/etc/yum.repos.d/{{ molecule_repo_file }}.repo"
        line: "# lynis community repository"
        state: present
      check_mode: true
      register: molecule_repository_yum
      failed_when: (molecule_repository_yum is changed) or (molecule_repository_yum is failed)
      when:
        - ansible_distribution in [ "RedHat", "CentOS", "Rocky", "AlmaLinux", "Fedora" ]

    - name: Check if {{ molecule_repo_package }} is installed
      ansible.builtin.package:
        name: "{{ molecule_repo_package }}"
        state: present
      register: molecule_package
      failed_when: (molecule_package is changed) or (molecule_package is failed)

    - name: "Check if custom profile file exists"
      ansible.builtin.lineinfile:
        name: '/etc/lynis/ansible.prf'
        line: "# Lynis Custom Options"
        state: present
      check_mode: true
      register: molecule_cron_file
      failed_when: (molecule_cron_file is changed) or (molecule_cron_file is failed)

    - name: "Check if cronjob file exists"
      ansible.builtin.lineinfile:
        name: '/usr/local/bin/lynis_scan_cron.sh'
        line: 'AUDITOR="automated"'
        state: present
      check_mode: true
      register: molecule_cron_file
      failed_when: (molecule_cron_file is changed) or (molecule_cron_file is failed)

    - name: "Check if cronjob exists"
      ansible.builtin.cron:
        name: "Launch Lynis security audit"
        minute: "5"
        hour: "0"
        day: "*"
        month: "*"
        weekday: "0"
        cron_file: "lynis"
        user: "root"
        job: "/usr/local/bin/lynis_scan_cron.sh 2>&1 | logger"
      check_mode: true
      register: molecule_cron
      failed_when: (molecule_cron is changed) or (molecule_cron is failed)

    - name: Test scan cron
      ansible.builtin.command: '/usr/local/bin/lynis_scan_cron.sh'
      register: molecule_script_test
      changed_when: molecule_script_test.rc != 0
